############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

# [[main]]
# name = "About"
# url = "about/"
# weight = 2

# [[main]]
# name = "Blog"
# url = "blog/"
# weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 3

# [[main]]
# weight = 4
# name = "Pages"
# hasChildren = true

[[main]]
weight = 4
name = "Team"
url = "team/"

# [[main]]
# weight = 5
# name = "Media"
# url = "media/"

[[main]]
weight = 6
name = "Contact"
url = "contact/"

# [[main]]
# weight = 6
# name = "NVIDIA Research"
# url = "https://www.nvidia.com/en-us/research/"

# [[main]]
# weight = 7
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "elements/"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3
