############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

# [[main]]
# name = "About"
# url = "about/"
# weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 2

# [[main]]
# name = "Elements"
# url = "elements/"
# weight = 3

# [[main]]
# weight = 4
# name = "Pages"
# hasChildren = true

[[main]]
weight = 3
name = "Authors"
url = "authors/"

[[main]]
weight = 4
name = "Contact"
url = "contact/"

[[main]]
weight = 5
name = "NVIDIA Research"
url = "https://www.nvidia.com/en-us/research/"

# [[main]]
# weight = 7
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "elements/"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3
